# Assignment 23


# Q1. If you have any, what are your choices for increasing the comparison between different figures on the same graph?

In [25]:
# Ans : Bar charts are good for comparisons, while line charts work better for trends. Scatter plot charts are good
#       for relationships and distributions, but pie charts should be used only for simple compositions — never for 
#       comparisons or distributions.

# Q2. Can you explain the benefit of compound interest over a higher rate of interest that does not compound after reading this chapter?

In [26]:
# Ans : Compound interest makes your money grow faster because interest is calculated on the accumulated interest 
#       over time as well as on your original principal. Compounding can create a snowball effect, as the original
#       investments plus the income earned from those investments grow together.

# Q3. What is a histogram, exactly? Name a numpy method for creating such a graph.

In [13]:
# Ans : Histogram is a type of a plot which hold the total number of counts or the percentile value in y-axis w.r.t.
#       corresponding x-variables. When we say the number of counts it means that for a particular range in x-axis
#       what will be the number of counts of the data points. When we talk about percentile it shows the probability
#       occurrence of the x-variable or what percentage of data are below that particular percetile value w.r.t.
#       particular x-variable range. Numpy has a built-in numpy. histogram() function.

# Q4. If necessary, how do you change the aspect ratios between the X and Y axes?

In [27]:
# Ans : We can use figure(figsize=(10,8)) function inside the matplot.pyplot library which we scale 
#       down or up the graph.
figure(figsize=(10,8))

NameError: name 'figure' is not defined

# Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.

In [28]:
# Ans : 
import numpy as np
a1=np.array([[1,2,3],[4,5,6],[6,7,8]])
a2=np.array([[10,20,30],[40,50,60],[60,70,80]])

# suppose above are the two arrays of shape 3 x 3
print(a1)
print()
print(a2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]

[[10 20 30]
 [40 50 60]
 [60 70 80]]


In [32]:
#standard multiplication
a1*a2

# When we do standard multiplication in that case values of the same indexes in the array will get multiply. 
# Like in above example. A1(i,j) x A2(i,j)
# dot product
np.dot(a1,a2)

# In case of dot product vector, multiplication will take place between row of first array and column of secodn array 
# .respectively. Like first row of array a1 will be multiply by column value of array a2 one by one and then added.
#outer multiplication
np.outer(a1,a2)

array([[ 10,  20,  30,  40,  50,  60,  60,  70,  80],
       [ 20,  40,  60,  80, 100, 120, 120, 140, 160],
       [ 30,  60,  90, 120, 150, 180, 180, 210, 240],
       [ 40,  80, 120, 160, 200, 240, 240, 280, 320],
       [ 50, 100, 150, 200, 250, 300, 300, 350, 400],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 70, 140, 210, 280, 350, 420, 420, 490, 560],
       [ 80, 160, 240, 320, 400, 480, 480, 560, 640]])

# Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?

In [33]:
# Ans : np.pmt(rate, nper, pv) function we will be using in order to calculate monthly mortgage payment before
#       you purchase a house
#       rate = The periodic interest rate
#       nper = The number of payment periods
#       pv = The total value of the mortgage loan

# Q7. Can array-to-scalar operations use combined operation-assign operators (such as += or *=)? What is the outcome?

In [6]:
# Ans : It will do the operation as per operators. Like if we use + operand it will update the current array by adding 
#       and when we use '*', it will update by multiplying.
#      Example :
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
a+=1
print(a)
a*=2
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Q8. Does a numpy array contain fixed-length strings? What happens if you allocate a longer string to one of these arrays?

In [8]:
# Ans : Yes it is possible that we can include a string of fixed length in numpy array. The dtype of any numpy array 
#       containing string values is the maximum length of any string present in the array.
#       Once set, it will only be able to store new string having length not more than the maximum length at the time 
#       of the creation. If we try to reassign some another string value having length greater than the maximum length
#       of the existing elements, it simply discards all the values beyond the maximum length accept upto those values 
#       which are under the limit.
import numpy as np
name = np.array(['ram', 'mohan', 'shiva'])
name

array(['ram', 'mohan', 'shiva'], dtype='<U5')

In [9]:
name[name=='ram']='undertaker'
print(name)

['under' 'mohan' 'shiva']


# Q9. What happens when you combine two numpy arrays using an operation like addition (+) or multiplication (*)? What are the conditions for combining two numpy arrays?

In [10]:
# Ans : It will simply add or multiply element to element at same position.The only requirement which must be met are:
#      1)Data type should be same.
#      2) Shape of the two matrices must be same
#      Example is as follows :
a1=a
a1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [11]:
a2=a+2
a2

array([[ 4,  6,  8],
       [10, 12, 14],
       [16, 18, 20]])

In [12]:
a1+a2

array([[ 6, 10, 14],
       [18, 22, 26],
       [30, 34, 38]])

In [15]:
a1*a2

array([[  8,  24,  48],
       [ 80, 120, 168],
       [224, 288, 360]])

# Q10. What is the best way to use a Boolean array to mask another array?

In [17]:
# Ans : 
y = np.array([True,True,False,True])          
x = np.array([1,2,3,4])         
m = np.ma.masked_where(x>2,y)  
print(list(m))
print(m.ndim)

[True, True, masked, masked]
1


# Q11. What are three different ways to get the standard deviation of a wide collection of data using both standard Python and its packages? Sort the three of them by how quickly they execute.

In [22]:
# Ans : Standard deviation can be calculated in many ways. If wee see the formula of SD, it says 
#       std= Square Root of [ Summation of [square of (x-mean)/number of observation] ] .So this can be achive by:
#       1)Using math module :
import math
N = 1
avg=a
total=N
x=[1,2]
SD=math.sqrt((1-a)**2+(2-a)**2/N)

TypeError: only size-1 arrays can be converted to Python scalars

In [23]:
#       2)Using Numpy Array package
import numpy as np
SD=np.std(x)

In [24]:
#       3) General calculation without using any package
SD= (((1-avg)**2 + (2-avg)**2)/N)**1/2