# Assignment 24


# Q1. Is it permissible to use several import statements to import the same module? What would the goal be? Can you think of a situation where it would be beneficial?

In [35]:
# Ans : Yes we can use more than one import statement to import the same module more than once.
#       This is com einto action when support we want to import some other function or class from the base 
#       class of any module for example.
#       from sklearn.preprocessing import LabelEncoder
#       from sklearn.linear_model import LinearRegression

# Q2. What are some of a module's characteristics? (Name at least one.)

In [36]:
# Ans : name : It returns the name of the module. doc : It denotes the documentation string line written in a module 
#       code. file : It holds the name and path of the module file from which it is loaded . dict : It return a 
#       dictionary object of module attributes, functions and other definitions and their respective values.

# Q3. Circular importing, such as when two modules import each other, can lead to dependencies and bugs that aren't visible. How can you go about creating a program that avoids mutual importing?

In [37]:
# Ans : Circular importing means importing the two modules in each other. If suppose we are wokring in MOD1.py file 
#       and it is importing some function say F2() from some other module say MOD2.PY file or we can do vice-versa. 
#       What will happen is: This will give an import error. This is because when we import F2() function from module 
#       MOD2.py, then this will execute MOD2.py file. And in MOD2.py file there is an another statement of importing
#       MOD1.py module. This will result in endless loop. To avoid this error just do one thing- We can use if 
#       name == 'main'.In the function, you can't directly refer to the function in the program. The addition of 
#       this sentence avoids the endless loop of the program

# Q4. Why is _ all _ in Python?

In [39]:
# Ans : It specifies all the modules present in the particular library and those can be called when we use import *

# Q5. Compare and contrast the three types of array multiplication between two numpy arrays: dot product, outer product, and regular multiplication of two numpy arrays.

In [28]:
# Ans : 
import numpy as np
a1=np.array([[1,2,3],[4,5,6],[6,7,8]])
a2=np.array([[10,20,30],[40,50,60],[60,70,80]])

# suppose above are the two arrays of shape 3 x 3
print(a1)
print()
print(a2)

[[1 2 3]
 [4 5 6]
 [6 7 8]]

[[10 20 30]
 [40 50 60]
 [60 70 80]]


In [32]:
#standard multiplication
a1*a2

# When we do standard multiplication in that case values of the same indexes in the array will get multiply. 
# Like in above example. A1(i,j) x A2(i,j)
# dot product
np.dot(a1,a2)

# In case of dot product vector, multiplication will take place between row of first array and column of secodn array 
# .respectively. Like first row of array a1 will be multiply by column value of array a2 one by one and then added.
#outer multiplication
np.outer(a1,a2)

array([[ 10,  20,  30,  40,  50,  60,  60,  70,  80],
       [ 20,  40,  60,  80, 100, 120, 120, 140, 160],
       [ 30,  60,  90, 120, 150, 180, 180, 210, 240],
       [ 40,  80, 120, 160, 200, 240, 240, 280, 320],
       [ 50, 100, 150, 200, 250, 300, 300, 350, 400],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 60, 120, 180, 240, 300, 360, 360, 420, 480],
       [ 70, 140, 210, 280, 350, 420, 420, 490, 560],
       [ 80, 160, 240, 320, 400, 480, 480, 560, 640]])

# Q6. Before you buy a home, which numpy function will you use to measure your monthly mortgage payment?

In [33]:
# Ans : np.pmt(rate, nper, pv) function we will be using in order to calculate monthly mortgage payment before
#       you purchase a house
#       rate = The periodic interest rate
#       nper = The number of payment periods
#       pv = The total value of the mortgage loan

# Q7. Can string data be stored in numpy arrays? If so, list at least one restriction that applies to this data.

In [34]:
# Ans : Yes an array can store the string.The limitation which imposed on the string data is, whenever we store the
#       data of string dtype then it should should keep in mind that the string which is having the maximum length is
#       the limit.
#       The dtype value is the maximum length of a string in such data. Meaning suppose if any new string we wanted 
#       to add, then we can add only that string which have the length either equal to that dtype value or less than
#       that. If any string which are adding and if its length is more than the dtype value then it will only accpet 
#        to maximum length and rest of the characters will not be included.